version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # subquery-node-evm:
  #   image: subquerynetwork/subql-node-ethereum:latest
  #   restart: unless-stopped
  #   environment:
  #     DB_USER: postgres
  #     DB_PASS: postgres
  #     DB_DATABASE: postgres
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #   volumes:
  #     - ./:/app
  #   command:
  #     - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
  #     - --multi-chain
  #     - --db-schema=multi-chain
  #     - -f=app/ethereum.yaml
  #     - --allow-schema-migration
  #     - --unfinalized-blocks=false
  #     - --unsafe
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
  #     interval: 3s
  #     timeout: 5s
  #     retries: 10

  subquery-node-avail:
    image: subquerynetwork/subql-node-substrate:latest
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - reindex
      - --multi-chain
      - --db-schema=multi-chain
      - -f=app/avail.yaml
      - --allow-schema-migration
      - --unfinalized-blocks=false
      - --batch-size=30
      - --unsafe
      - --worker=3
      - --historical="height"
      - --disable-historical=false
      - --targetHeight=90115

    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=multi-chain
      - --playground
